services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: app-ubs
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx/logs:/var/log/nginx
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/supervisor/logs:/supervisor/logs
        ports:
            - ${APP_PORT}:80
        env_file:
            - ./.env
        networks:
            - proxy

    mysql:
        image: mysql:latest
        container_name: mysql-ubs
        platform: linux/amd64
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks:
            - proxy

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-ubs
        platform: linux/amd64
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${PHPMYADMIN_PORT}:80
        networks:
            - proxy

    redis:
        image: redis:latest
        container_name: redis-ubs
        restart: always
        volumes:
            - ./docker/redis/data:/data
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - proxy

networks:
    proxy:
        external: true